name: news
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  #Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  #API
  dio: ^5.4.3+1

  #State Management
  bloc: ^8.1.4
  flutter_bloc: ^8.1.5

  #Utils
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  freezed: ^2.5.2
  equatable: ^2.0.5
  date_time_format: ^2.0.1
  webview_flutter: ^4.8.0
  webview_flutter_android: ^3.16.3
  webview_flutter_wkwebview: ^3.13.1
  uuid: ^4.4.0

  #UI
  contained_tab_bar_view: ^0.8.0
  card_loading: ^0.3.2
  toastification: ^2.0.0
  salomon_bottom_bar: ^3.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.9
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
